version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express-server-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-this}
    volumes:
      - .:/app
      - /app/node_modules
      - ./database.sqlite:/app/database.sqlite
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge
