version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-this}
    volumes:
      - ./data:/app/data
      - ./database.sqlite:/app/database.sqlite
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
