services:
  - type: web
    name: express-server
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: true
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
